// <auto-generated />
namespace FCK.Studio.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UptUnitAndDoorcard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UptUnitAndDoorcard));
        
        string IMigrationMetadata.Id
        {
            get { return "201809020717117_UptUnitAndDoorcard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
