// <auto-generated />
namespace FCK.Studio.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UptHouses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UptHouses));
        
        string IMigrationMetadata.Id
        {
            get { return "201805241405001_UptHouses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
